kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: periscope-binding
  namespace: periscope
subjects:
- kind: ServiceAccount
  name: periscope-sa
  namespace: periscope
roleRef:
  kind: Role
  name: periscope-default
  apiGroup: rbac.authorization.k8s.io